### ISSUE TITLE
Mac sendMIDI Will Not Install with Homebrew

### ISSUE THREAD

**Issue by playinmyblues** [gbevin/homebrew-tools#1]
Below are the command I use to install sendMIDI and the error message that results:

$ brew install gbevin/tools/sendmidi
Error, but only the last section :
==> xcodebuild -project ./Builds/MacOSX/sendmidi.xcodeproj -configuration Releas
Last 15 lines from /Users/robertbfleming/Library/Logs/Homebrew/sendmidi/01.xcodebuild:
2018-08-26 15:27:09 -0300

xcodebuild
-project
./Builds/MacOSX/sendmidi.xcodeproj
-configuration
Release
SYMROOT=build

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/gbevin/homebrew-tools/issues

**Comment by jenlun** [comment]
Set the active developer directory to the full XCode installation by calling
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
